name: CodeProject AI.Server (CPU) rpi64
version: rpi64-2.1.10
url: https://hub.docker.com/r/codeproject/ai-server
image: codeproject/ai-server
panel_icon: mdi:face-recognition
slug: ai-server
description: standalone open-source AI server for raspberryPi 4
arch:
  - arm64
startup: application
boot: auto
ingress: true
ingress_port: 5000
ports:
  5000/tcp: 5000
ports_description:
  5000/tcp: Web interface (not required for Home Assistant ingress)
map:
  - config:rw
environment:
  HA_ADDON: 'true'
  DATA_DIR: "/config/ai-server/data"
  MODULES_PATH: "/config/ai-server/modules"
schema:
  CONFIG_PATH: str
  MODULES_PATH: str
