name: Double Take
version: 1.13.11.8
image: ghcr.io/skrashevich/hassio-addon-double-take-{arch}
url: https://double-take.site/redirect.php?location=github
panel_icon: mdi:face-recognition
slug: double-take
description: Unified UI and API for processing and training images for facial recognition
arch:
  - amd64
  - aarch64
  - armv7
startup: application
boot: auto
ingress: true
tmpfs: true
init: false
full_access: false
privileged:
  - SYS_ADMIN
ingress_port: 3000
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: Web interface (not required for Home Assistant ingress)
map:
  - media:rw
  - config:rw
environment:
  HA_ADDON: "true"
options:
  STORAGE_PATH: "/config/double-take"
  CONFIG_PATH: "/config/double-take"
  SECRETS_PATH: "/config/double-take"
  MEDIA_PATH: "/media/double-take"
  IPFILTER: true
schema:
  STORAGE_PATH: str
  CONFIG_PATH: str
  SECRETS_PATH: str
  MEDIA_PATH: str
  IPFILTER: bool
